### ISSUE TITLE
希望作者添加下这几个应用

### ISSUE THREAD

**Issue by PingZi-Wing** [eyelly-wu/appstore-discounts#4]
1.Dark Reader for Safari，AppID：1438243180，追踪本体价格，商店链接 https://apps.apple.com/us/app/dark-reader-for-safari/id1438243180?l=zh-Hans-CN
2.Stay for Safari，AppID：1591620171，追踪内购价格，商店链接 https://apps.apple.com/us/app/stay-for-safari-%E6%B5%8F%E8%A7%88%E5%99%A8%E4%BC%B4%E4%BE%A3/id1591620171?l=zh-Hans-CN
3.Noir，Mac版，AppID：1592917505，追踪本体价格，商店链接 https://apps.apple.com/us/app/noir-%E4%B8%BAsafari%E6%B7%BB%E5%8A%A0%E6%B7%B1%E8%89%B2%E6%A8%A1%E5%BC%8F/id1592917505?l=zh-Hans-CN&mt=12
4.Noir，iOS、iPadOS版，AppID：1581140954，追踪本体价格，商店链接 https://apps.apple.com/cn/app/noir-%E4%B8%BAsafari%E6%B7%BB%E5%8A%A0%E6%B7%B1%E8%89%B2%E6%A8%A1%E5%BC%8F/id1581140954

**Comment by eyelly-wu** [comment]
感谢反馈，已添加
